
insert into neuroid.clients (clientName, lastmodifieduser, lastModifiedDate) values
('EDMine', 1, date_sub(now(), interval 10 day)),
('Currim\'s minions', 1, date_sub(now(), interval 10 day)),
('DBCactus', 1, date_sub(now(), interval 10 day)),
('Datacats', 1, date_sub(now(), interval 10 day)),
('WildCards', 1, date_sub(now(), interval 10 day)),
('EDM\'s Greatest Hits', 1, date_sub(now(), interval 10 day)),
('Global Enterprise Management', 1, date_sub(now(), interval 10 day)),
('Databots', 1, date_sub(now(), interval 10 day)),
('Invalid Identifier', 1, date_sub(now(), interval 10 day));


insert into neuroid.industry (industryname, industrydesc, lastModifiedDate, lastmodifieduser) values
('Banking', 'Lorem ipsum dolor sit amet', date_sub(now(), interval 10 day), 1),
('Healthcare', 'Lorem ipsum dolor sit amet', date_sub(now(), interval 10 day), 1),
('Industrial Manufacturing', '', date_sub(now(), interval 10 day), 1),
('Aerospace & Defence', '', date_sub(now(), interval 10 day), 1),
('Insurance', '', date_sub(now(), interval 10 day), 1),
('Automotive & Transportation', '', date_sub(now(), interval 10 day), 1);


insert into neuroid.projects (projectName, clientID, lastModifiedDate, lastmodifieduser) values
('A grade', 9, date_sub(now(), interval 10 day), 1),
('Cartesian Product', 4, date_sub(now(), interval 10 day), 1),
('Project A', 1, date_sub(now(), interval 10 day), 1),
('Project B', 2, date_sub(now(), interval 10 day), 1),
('Project C', 3, date_sub(now(), interval 10 day), 1),
('Project D', 4, date_sub(now(), interval 10 day), 1),
('Project E', 5, date_sub(now(), interval 10 day), 1),
('Project F', 6, date_sub(now(), interval 10 day), 1),
('Project G', 7, date_sub(now(), interval 10 day), 1),
('Project H', 8, date_sub(now(), interval 10 day), 1),
('Project I', 1, date_sub(now(), interval 10 day), 1),
('Project J', 2, date_sub(now(), interval 10 day), 1),
('Project K', 3, date_sub(now(), interval 10 day), 1),
('Project L', 4, date_sub(now(), interval 10 day), 1),
('Project M', 5, date_sub(now(), interval 10 day), 1),
('Project N', 6, date_sub(now(), interval 10 day), 1),
('Project O', 7, date_sub(now(), interval 10 day), 1),
('Project P', 8, date_sub(now(), interval 10 day), 1),
('Project Q', 1, date_sub(now(), interval 10 day), 1),
('Project R', 2, date_sub(now(), interval 10 day), 1),
('Project S', 3, date_sub(now(), interval 10 day), 1),
('Project T', 4, date_sub(now(), interval 10 day), 1),
('Project U', 5, date_sub(now(), interval 10 day), 1),
('Project V', 6, date_sub(now(), interval 10 day), 1),
('Project W', 7, date_sub(now(), interval 10 day), 1),
('Project X', 8, date_sub(now(), interval 10 day), 1),
('Project Y', 1, date_sub(now(), interval 10 day), 1),
('Project Z', 2, date_sub(now(), interval 10 day), 1);

insert into neuroid.topic_tags (topicName, topicDescription, lastModifiedDate, lastmodifieduser) values
('Tag 1', 'Some text goes here 1', date_sub(now(), interval 10 day), 1),
('Tag 2', 'Some text goes here 2', date_sub(now(), interval 10 day), 1),
('Tag 3', 'Some text goes here 3', date_sub(now(), interval 10 day), 1),
('Tag 4', 'Some text goes here 4', date_sub(now(), interval 10 day), 1),
('Tag 5', 'Some text goes here 5', date_sub(now(), interval 10 day), 1),
('Tag 6', 'Some text goes here 6', date_sub(now(), interval 10 day), 1),
('Tag 7', 'Some text goes here 7', date_sub(now(), interval 10 day), 1),
('Tag 8', 'Some text goes here 8', date_sub(now(), interval 10 day), 1),
('Tag 9', 'Some text goes here 9', date_sub(now(), interval 10 day), 1),
('Tag 10', 'Some text goes here 10', date_sub(now(), interval 10 day), 1),
('Tag 11', 'Some text goes here 11', date_sub(now(), interval 10 day), 1),
('Tag 12', 'Some text goes here 12', date_sub(now(), interval 10 day), 1),
('Tag 13', 'Some text goes here 13', date_sub(now(), interval 10 day), 1),
('Tag 14', 'Some text goes here 14', date_sub(now(), interval 10 day), 1),
('Tag 15', 'Some text goes here 15', date_sub(now(), interval 10 day), 1),
('Tag 16', 'Some text goes here 16', date_sub(now(), interval 10 day), 1),
('Tag 17', 'Some text goes here 17', date_sub(now(), interval 10 day), 1),
('Tag 18', 'Some text goes here 18', date_sub(now(), interval 10 day), 1),
('Tag 19', 'Some text goes here 19', date_sub(now(), interval 10 day), 1),
('Tag 20', 'Some text goes here 20', date_sub(now(), interval 10 day), 1),
('Tag 21', 'Some text goes here 21', date_sub(now(), interval 10 day), 1),
('Tag 22', 'Some text goes here 22', date_sub(now(), interval 10 day), 1),
('Tag 23', 'Some text goes here 23', date_sub(now(), interval 10 day), 1),
('Tag 24', 'Some text goes here 24', date_sub(now(), interval 10 day), 1),
('Tag 25', 'Some text goes here 25', date_sub(now(), interval 10 day), 1);

insert into neuroid.question_types (questionType) values
('Risk'),
('Persona'),
('Baseline'),
('EDM'),
('Invalid');

insert into neuroid.questions (lastModifiedUser, lastModifiedDate, questionTypeID) values
(1, date_sub(now(), interval 10 day), 1),
(1, date_sub(now(), interval 10 day), 2),
(1, date_sub(now(), interval 10 day), 3),
(1, date_sub(now(), interval 10 day), 4),
(1, date_sub(now(), interval 10 day), 5),
(1, date_sub(now(), interval 10 day), 1),
(1, date_sub(now(), interval 10 day), 2),
(1, date_sub(now(), interval 10 day), 3),
(1, date_sub(now(), interval 10 day), 4),
(1, date_sub(now(), interval 10 day), 5),
(1, date_sub(now(), interval 10 day), 1),
(1, date_sub(now(), interval 10 day), 2),
(1, date_sub(now(), interval 10 day), 3),
(1, date_sub(now(), interval 10 day), 4),
(1, date_sub(now(), interval 10 day), 5),
(1, date_sub(now(), interval 10 day), 1);



insert into neuroid.question_version (questionID, versionid, questionText, lastModifiedUser, lastModifiedDate) values
(1,1,'What is your name?',1, date_sub(now(), interval 10 day)),
(1,2,'What is your first name?',1, date_sub(now(), interval 10 day)),
(1,3,'What is your last name?',1, date_sub(now(), interval 10 day)),
(2,1,'What is your Age?',1, date_sub(now(), interval 10 day)),
(3,1,'Do you take the shampoo and conditioner bottles from hotels?',1, date_sub(now(), interval 10 day)),
(3,2,'Do you take the conditioner bottles from hotels?',1, date_sub(now(), interval 10 day)),
(4,1,'Is the Earth flat?',1, date_sub(now(), interval 10 day)),
(5,1,'Question 5?',1, date_sub(now(), interval 10 day)),
(6,1,'What are your super powers?',1,date_sub(now(), interval 10 day)),
(7,1,'Pineapple or Pepperoni?',1,date_sub(now(), interval 10 day)),
(8,1,'Question 8?',1,date_sub(now(), interval 10 day)),
(9,1,'Did you complete the TCE for EDM?',1,date_sub(now(), interval 10 day)),
(10,1,'Question 10?',1,date_sub(now(), interval 10 day)),
(11,1,'When was the last time you climbed a tree?',1,date_sub(now(), interval 10 day)),
(12,1,'Do you like carrots?',1,date_sub(now(), interval 10 day)),
(13,1,'Where is your nearest 7-11?',1,date_sub(now(), interval 10 day)),
(14,1,'Question 14?',1,date_sub(now(), interval 10 day)),
(15,1,'Question 15?',1,date_sub(now(), interval 10 day)),
(16,1,'Question 16?',1,date_sub(now(), interval 10 day));


insert into neuroid.subquestions (questionID, versionid, subquestionID, subversionid) values
(1,1,1,2),
(1,1,1,3);


insert into neuroid.industry_question (industryid, questionid, versionid, dateadded) values
(1,1,3,date_sub(curdate(), interval 10 day)),
(1,2,1,date_sub(curdate(), interval 10 day)),
(1,3,2,date_sub(curdate(), interval 8 day)),
(1,4,1,date_sub(curdate(), interval 8 day)),
(1,5,1,date_sub(curdate(), interval 8 day)),
(2,3,1,date_sub(curdate(), interval 10 day)),
(2,4,1,date_sub(curdate(), interval 10 day)),
(2,5,1,date_sub(curdate(), interval 7 day)),
(3,7,1,date_sub(curdate(), interval 10 day)),
(3,11,1,date_sub(curdate(), interval 3 day)),
(4,13,1,date_sub(curdate(), interval 10 day)),
(4,14,1,date_sub(curdate(), interval 2 day)),
(4,12,1,date_sub(curdate(), interval 2 day)),
(4,1,1,date_sub(curdate(), interval 2 day)),
(5,9,1,date_sub(curdate(), interval 10 day)),
(5,10,1,date_sub(curdate(), interval 10 day)),
(5,3,1,date_sub(curdate(), interval 10 day)),
(6,2,1,date_sub(curdate(), interval 10 day));

insert into neuroid.project_question (projectID, questionid, versionid, dateadded) values
(1,1,3,date_sub(curdate(), interval 10 day)),
(1,2,1,date_sub(curdate(), interval 10 day)),
(1,3,2,date_sub(curdate(), interval 8 day)),
(1,4,1,date_sub(curdate(), interval 8 day)),
(1,5,1,date_sub(curdate(), interval 8 day)),
(2,3,1,date_sub(curdate(), interval 10 day)),
(2,4,1,date_sub(curdate(), interval 7 day)),
(2,5,1,date_sub(curdate(), interval 7 day)),
(3,7,1,date_sub(curdate(), interval 10 day)),
(3,11,1,date_sub(curdate(), interval 2 day)),
(4,13,1,date_sub(curdate(), interval 10 day)),
(4,14,1,date_sub(curdate(), interval 5 day)),
(4,12,1,date_sub(curdate(), interval 5 day)),
(4,1,1,date_sub(curdate(), interval 5 day)),
(5,9,1,date_sub(curdate(), interval 10 day)),
(5,10,1,date_sub(curdate(), interval 10 day)),
(5,3,1,date_sub(curdate(), interval 10 day)),
(6,2,1,date_sub(curdate(), interval 10 day));

insert into neuroid.topic_question (topicID, questionid, versionid) values
(1,1,3),
(1,2,1),
(1,3,2),
(1,4,1),
(1,5,1),
(1,10,1),
(1,11,1),
(2,10,1),
(2,11,1),
(2,1,1),
(2,2,1),
(2,3,1),
(2,4,1),
(3,2,1),
(3,3,1),
(3,1,1),
(3,4,1),
(3,5,1),
(4,6,1),
(4,7,1),
(4,8,1),
(4,9,1),
(4,1,1),
(4,2,1),
(5,3,1),
(5,4,1),
(5,5,1),
(5,6,1),
(5,7,1),
(5,8,1),
(5,1,1),
(6,2,1),
(6,3,1),
(6,4,1),
(6,5,1),
(7,6,1),
(7,8,1),
(7,9,1),
(7,1,1),
(7,2,1),
(8,3,1),
(8,4,1),
(8,5,1),
(8,1,1),
(9,5,1),
(9,7,1),
(9,8,1),
(9,9,1),
(9,2,1),
(10,1,1),
(10,3,1),
(10,4,1),
(10,5,1),
(10,7,1),
(10,8,1),
(10,9,1);

insert into neuroid.project_history values
(1,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 9 day), 1,3, date_sub(curdate(), interval 10 day)),
(1,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 9 day), 2,1, date_sub(curdate(), interval 10 day)),
(1,date_sub(curdate(), interval 8 day),null, 1,3, date_sub(curdate(), interval 10 day)),
(1,date_sub(curdate(), interval 8 day),null, 2,1, date_sub(curdate(), interval 10 day)),
(1,date_sub(curdate(), interval 8 day),null, 3,2, date_sub(curdate(), interval 8 day)),
(1,date_sub(curdate(), interval 8 day),null, 4,1, date_sub(curdate(), interval 8 day)),
(1,date_sub(curdate(), interval 8 day),null, 5,1, date_sub(curdate(), interval 8 day)),
(2,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 8 day), 3,1, date_sub(curdate(), interval 10 day)),
(2,date_sub(curdate(), interval 7 day),null, 3,1, date_sub(curdate(), interval 10 day)),
(2,date_sub(curdate(), interval 7 day),null, 4,1, date_sub(curdate(), interval 7 day)),
(2,date_sub(curdate(), interval 7 day),null, 5,1, date_sub(curdate(), interval 7 day)),
(3,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 3 day), 7,1, date_sub(curdate(), interval 10 day)),
(3,date_sub(curdate(), interval 2 day),null, 7,1, date_sub(curdate(), interval 10 day)),
(3,date_sub(curdate(), interval 2 day),null, 4,1, date_sub(curdate(), interval 2 day)),
(4,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 6 day), 13,1, date_sub(curdate(), interval 10 day)),
(4,date_sub(curdate(), interval 5 day),null, 13,1, date_sub(curdate(), interval 10 day)),
(4,date_sub(curdate(), interval 5 day),null, 14,1, date_sub(curdate(), interval 5 day)),
(4,date_sub(curdate(), interval 5 day),null, 12,1, date_sub(curdate(), interval 5 day)),
(4,date_sub(curdate(), interval 5 day),null, 1,1, date_sub(curdate(), interval 5 day)),
(5,date_sub(curdate(), interval 10 day),null, 9,1, date_sub(curdate(), interval 10 day)),
(5,date_sub(curdate(), interval 10 day),null, 10,1, date_sub(curdate(), interval 10 day)),
(5,date_sub(curdate(), interval 10 day),null, 3,1, date_sub(curdate(), interval 10 day)),
(6,date_sub(curdate(), interval 10 day),null, 2,1, date_sub(curdate(), interval 10 day));

insert into neuroid.industry_history values
(1,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 9 day), 1,3, date_sub(curdate(), interval 10 day)),
(1,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 9 day), 2,1, date_sub(curdate(), interval 10 day)),
(1,date_sub(curdate(), interval 8 day),null, 1,3, date_sub(curdate(), interval 10 day)),
(1,date_sub(curdate(), interval 8 day),null, 2,1, date_sub(curdate(), interval 10 day)),
(1,date_sub(curdate(), interval 8 day),null, 3,2, date_sub(curdate(), interval 8 day)),
(1,date_sub(curdate(), interval 8 day),null, 4,1, date_sub(curdate(), interval 8 day)),
(1,date_sub(curdate(), interval 8 day),null, 5,1, date_sub(curdate(), interval 8 day)),
(2,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 8 day), 3,1, date_sub(curdate(), interval 10 day)),
(2,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 8 day), 4,1, date_sub(curdate(), interval 7 day)),
(2,date_sub(curdate(), interval 7 day),null, 3,1, date_sub(curdate(), interval 10 day)),
(2,date_sub(curdate(), interval 7 day),null, 4,1, date_sub(curdate(), interval 10 day)),
(2,date_sub(curdate(), interval 7 day),null, 5,1, date_sub(curdate(), interval 7 day)),
(3,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 4 day), 7,1, date_sub(curdate(), interval 10 day)),
(3,date_sub(curdate(), interval 3 day),null, 7,1, date_sub(curdate(), interval 10 day)),
(3,date_sub(curdate(), interval 3 day),null, 11,1, date_sub(curdate(), interval 2 day)),
(4,date_sub(curdate(), interval 10 day),date_sub(curdate(), interval 3 day), 13,1, date_sub(curdate(), interval 10 day)),
(4,date_sub(curdate(), interval 2 day),null, 13,1, date_sub(curdate(), interval 10 day)),
(4,date_sub(curdate(), interval 2 day),null, 14,1, date_sub(curdate(), interval 5 day)),
(4,date_sub(curdate(), interval 2 day),null, 12,1, date_sub(curdate(), interval 5 day)),
(4,date_sub(curdate(), interval 2 day),null, 1,1, date_sub(curdate(), interval 5 day)),
(5,date_sub(curdate(), interval 10 day),null, 9,1, date_sub(curdate(), interval 10 day)),
(5,date_sub(curdate(), interval 10 day),null, 10,1, date_sub(curdate(), interval 10 day)),
(5,date_sub(curdate(), interval 10 day),null, 3,1, date_sub(curdate(), interval 10 day)),
(6,date_sub(curdate(), interval 10 day),null, 2,1, date_sub(curdate(), interval 10 day));
